name: Bug Report
description: File a bug report
title: "Bug report"
labels: [":bug: bug", ":ballot_box: needs triage"]
assignees:
  - Secret-chest
body:
  - type: markdown
    attributes:
      value: |
        File a bug report here.
  - type: textarea
    id: what-was-expected
    attributes:
      label: What did you expect to happen?
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What did actually happen?
      placeholder: What did happen that you weren't expecting?
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How did you make that happen?
      placeholder: Tell us how to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Python errors
      description: Please copy and paste any relevant errors.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Latest version
      description: You must be running the latest Scratch2Python version.
      options:
        - label: I am running the **latest version**
          required: true
